import { MainToolbar } from "@canonical/maas-react-components";
import {
  Col,
  ContextualMenu,
  MainTable,
  Row,
  Strip,
  Spinner,
  Button,
} from "@canonical/react-components";
import { useSelector } from "react-redux";
import { Link } from "react-router";

import AddRecordForm from "../DomainDetailsHeader/AddRecordForm";

import DeleteRecordForm from "./DeleteRecordForm";
import EditRecordForm from "./EditRecordForm";

import { useGetIsSuperUser } from "@/app/api/query/auth";
import { useSidePanel } from "@/app/base/side-panel-context-new";
import urls from "@/app/base/urls";
import domainsSelectors from "@/app/store/domain/selectors";
import type { Domain } from "@/app/store/domain/types";
import { isDomainDetails } from "@/app/store/domain/utils";
import type { RootState } from "@/app/store/root/types";
import { NodeType } from "@/app/store/types/node";

export enum Labels {
  NoRecords = "Domain contains no records.",
}

type Props = {
  id: Domain["id"];
};

const ResourceRecords = ({ id }: Props): React.ReactElement | null => {
  const { openSidePanel } = useSidePanel();
  const domain = useSelector((state: RootState) =>
    domainsSelectors.getById(state, id)
  );
  const loading = useSelector(domainsSelectors.loading);

  const isSuperUser = useGetIsSuperUser();

  if (loading) {
    return (
      <Strip shallow>
        <Spinner text="Loading..." />
      </Strip>
    );
  }
  if (!isDomainDetails(domain)) {
    return null;
  }

  const headers = [
    {
      content: "Name",
      sortKey: "name",
    },
    {
      content: "Type",
      sortKey: "type",
    },
    {
      content: "TTL",
      sortKey: "ttl",
    },
    {
      content: "Data",
      sortKey: "data",
    },
    {
      content: "Actions",
      className: "u-align--right",
    },
  ];

  const rows = domain.rrsets.map((resource) => {
    let nameCell = <>{resource.name}</>;

    // We can't edit records that don't have a dnsresource_id.
    // (If the row doesn't have one, it has probably been automatically
    // generated by means of a deployed node, or some other reason.)
    const isAutogenerated = !resource.dnsresource_id;
    const canEdit = !isAutogenerated && isSuperUser.data;

    if (resource.node_type != null && resource.system_id !== null) {
      switch (resource.node_type) {
        case NodeType.MACHINE:
          nameCell = (
            <Link to={urls.machines.machine.index({ id: resource.system_id })}>
              {resource.name}
            </Link>
          );
          break;
        case NodeType.DEVICE:
          nameCell = (
            <Link to={urls.devices.device.index({ id: resource.system_id })}>
              {resource.name}
            </Link>
          );
          break;
        case NodeType.RACK_CONTROLLER:
        case NodeType.REGION_CONTROLLER:
        case NodeType.REGION_AND_RACK_CONTROLLER:
          nameCell = (
            <Link
              to={urls.controllers.controller.index({
                id: resource.system_id,
              })}
            >
              {resource.name}
            </Link>
          );
          break;
      }
    }

    return {
      columns: [
        {
          content: nameCell,
        },
        {
          content: resource.rrtype,
        },
        {
          content: resource.ttl || "(default)",
        },
        {
          content: resource.rrdata,
        },
        {
          content: (
            <ContextualMenu
              hasToggleIcon={true}
              links={[
                {
                  children: "Edit record...",
                  onClick: () => {
                    openSidePanel({
                      component: EditRecordForm,
                      title: "Edit Record",
                      props: {
                        id,
                        resource,
                      },
                    });
                  },
                },
                {
                  children: "Remove record...",
                  onClick: () => {
                    openSidePanel({
                      component: DeleteRecordForm,
                      title: "Delete Record",
                      props: {
                        id,
                        resource,
                      },
                    });
                  },
                },
              ]}
              toggleAppearance="base"
              toggleClassName="u-no-margin--bottom is-small is-dense"
              toggleDisabled={!canEdit}
            />
          ),
          className: "u-align--right",
        },
      ],
      sortData: {
        name: resource.name,
        type: resource.rrtype,
        ttl: resource.ttl,
        data: resource.rrdata,
      },
    };
  });

  return (
    <Strip shallow>
      <Row>
        <Col size={12}>
          <MainToolbar>
            <MainToolbar.Title className="p-heading--4">
              Resource records
            </MainToolbar.Title>
            <MainToolbar.Controls>
              <Button
                data-testid="add-record"
                key="add-record"
                onClick={() => {
                  openSidePanel({
                    component: AddRecordForm,
                    title: "Add record",
                    props: {
                      id,
                    },
                  });
                }}
              >
                Add record
              </Button>
            </MainToolbar.Controls>
          </MainToolbar>
          <MainTable
            className="p-table-expanding--light"
            defaultSort="name"
            defaultSortDirection="ascending"
            expanding
            headers={headers}
            paginate={50}
            rows={rows}
            sortable
          />
          {domain.rrsets.length === 0 && (
            <Strip rowClassName="u-align--center" shallow>
              <span data-testid="no-records">{Labels.NoRecords}</span>
            </Strip>
          )}
        </Col>
      </Row>
    </Strip>
  );
};

export default ResourceRecords;
