import { NodeActions } from "app/store/types/node";

export const MachineHeaderNames = {
  ABORT_MACHINE: "abortMachine",
  ACQUIRE_MACHINE: "acquireMachine",
  ADD_CHASSIS: "addChassis",
  ADD_MACHINE: "addMachine",
  CLONE_MACHINE: "cloneMachine",
  COMMISSION_MACHINE: "commissionMachine",
  DELETE_MACHINE: "deleteMachine",
  DEPLOY_MACHINE: "deployMachine",
  ENTER_RESCUE_MODE_MACHINE: "enterRescueModeMachine",
  EXIT_RESCUE_MODE_MACHINE: "exitRescueModeMachine",
  LOCK_MACHINE: "lockMachine",
  MARK_BROKEN_MACHINE: "markBrokenMachine",
  MARK_FIXED_MACHINE: "markFixedMachine",
  POWER_OFF_MACHINE: "powerOffMachine",
  POWER_ON_MACHINE: "powerOnMachine",
  OVERRIDE_FAILED_TESTING_MACHINE: "overrideFailedTestingMachine",
  RELEASE_MACHINE: "releaseMachine",
  SET_POOL_MACHINE: "setPoolMachine",
  SET_ZONE_MACHINE: "setZoneMachine",
  TAG_MACHINE: "tagMachine",
  TEST_MACHINE: "testMachine",
  UNLOCK_MACHINE: "unlockMachine",
} as const;

export const MachineHeaderActionMap = {
  [NodeActions.ABORT]: MachineHeaderNames.ABORT_MACHINE,
  [NodeActions.ACQUIRE]: MachineHeaderNames.ACQUIRE_MACHINE,
  [NodeActions.CLONE]: MachineHeaderNames.CLONE_MACHINE,
  [NodeActions.COMMISSION]: MachineHeaderNames.COMMISSION_MACHINE,
  [NodeActions.DELETE]: MachineHeaderNames.DELETE_MACHINE,
  [NodeActions.DEPLOY]: MachineHeaderNames.DEPLOY_MACHINE,
  [NodeActions.EXIT_RESCUE_MODE]: MachineHeaderNames.EXIT_RESCUE_MODE_MACHINE,
  [NodeActions.LOCK]: MachineHeaderNames.LOCK_MACHINE,
  [NodeActions.MARK_BROKEN]: MachineHeaderNames.MARK_BROKEN_MACHINE,
  [NodeActions.MARK_FIXED]: MachineHeaderNames.MARK_FIXED_MACHINE,
  [NodeActions.OFF]: MachineHeaderNames.POWER_OFF_MACHINE,
  [NodeActions.ON]: MachineHeaderNames.POWER_ON_MACHINE,
  [NodeActions.OVERRIDE_FAILED_TESTING]:
    MachineHeaderNames.OVERRIDE_FAILED_TESTING_MACHINE,
  [NodeActions.RELEASE]: MachineHeaderNames.RELEASE_MACHINE,
  [NodeActions.RESCUE_MODE]: MachineHeaderNames.ENTER_RESCUE_MODE_MACHINE,
  [NodeActions.SET_POOL]: MachineHeaderNames.SET_POOL_MACHINE,
  [NodeActions.SET_ZONE]: MachineHeaderNames.SET_ZONE_MACHINE,
  [NodeActions.TAG]: MachineHeaderNames.TAG_MACHINE,
  [NodeActions.TEST]: MachineHeaderNames.TEST_MACHINE,
  [NodeActions.UNLOCK]: MachineHeaderNames.UNLOCK_MACHINE,
} as const;
