// This file is auto-generated by @hey-api/openapi-ts

import type { Options } from "@hey-api/client-fetch";
import { queryOptions, type UseMutationOptions } from "@tanstack/react-query";

import {
  accessToken,
  login,
  listEvents,
  listFabrics,
  createFabric,
  deleteFabric,
  getFabric,
  updateFabric,
  listInterfaces,
  listFabricVlanSubnetIprange,
  createFabricVlanSubnetIprange,
  deleteFabricVlanSubnetIprange,
  updateFabricVlanSubnetIprange,
  getFabricVlanSubnetIprange,
  getMachinePowerParameters,
  listMachinePciDevices,
  listMachineUsbDevices,
  listMachines,
  listFabricVlanSubnetReservedIps,
  createFabricVlanSubnetReservedIp,
  deleteFabricVlanSubnetReservedIp,
  updateFabricVlanSubnetReservedIp,
  getFabricVlanSubnetReservedIp,
  listResourcePools,
  createResourcePool,
  getResourcePool,
  updateResourcePool,
  listSpaces,
  createSpace,
  deleteSpace,
  getSpace,
  updateSpace,
  getUserSslkeys,
  listFabricVlanSubnets,
  createFabricVlanSubnet,
  deleteFabricVlanSubnet,
  updateFabricVlanSubnet,
  getFabricVlanSubnet,
  getUserInfo,
  listUserSshkeys,
  getUserSshkey,
  listUsers,
  createUser,
  getUser,
  updateUser,
  listFabricVlans,
  createFabricVlan,
  deleteFabricVlan,
  getFabricVlan,
  updateFabricVlan,
  listZones,
  createZone,
  deleteZone,
  getZone,
  updateZone,
  client,
} from "../sdk.gen";
import type {
  AccessTokenData,
  LoginData,
  LoginError,
  LoginResponse,
  ListEventsData,
  ListFabricsData,
  CreateFabricData,
  CreateFabricError,
  CreateFabricResponse,
  DeleteFabricData,
  DeleteFabricError,
  DeleteFabricResponse,
  GetFabricData,
  UpdateFabricData,
  UpdateFabricError,
  UpdateFabricResponse,
  ListInterfacesData,
  ListFabricVlanSubnetIprangeData,
  CreateFabricVlanSubnetIprangeData,
  CreateFabricVlanSubnetIprangeError,
  CreateFabricVlanSubnetIprangeResponse,
  DeleteFabricVlanSubnetIprangeData,
  DeleteFabricVlanSubnetIprangeError,
  DeleteFabricVlanSubnetIprangeResponse,
  UpdateFabricVlanSubnetIprangeData,
  UpdateFabricVlanSubnetIprangeError,
  UpdateFabricVlanSubnetIprangeResponse,
  GetFabricVlanSubnetIprangeData,
  GetMachinePowerParametersData,
  ListMachinePciDevicesData,
  ListMachineUsbDevicesData,
  ListMachinesData,
  ListFabricVlanSubnetReservedIpsData,
  CreateFabricVlanSubnetReservedIpData,
  CreateFabricVlanSubnetReservedIpError,
  CreateFabricVlanSubnetReservedIpResponse,
  DeleteFabricVlanSubnetReservedIpData,
  DeleteFabricVlanSubnetReservedIpError,
  DeleteFabricVlanSubnetReservedIpResponse,
  UpdateFabricVlanSubnetReservedIpData,
  UpdateFabricVlanSubnetReservedIpError,
  UpdateFabricVlanSubnetReservedIpResponse,
  GetFabricVlanSubnetReservedIpData,
  ListResourcePoolsData,
  CreateResourcePoolData,
  CreateResourcePoolError,
  CreateResourcePoolResponse,
  GetResourcePoolData,
  UpdateResourcePoolData,
  UpdateResourcePoolError,
  UpdateResourcePoolResponse,
  ListSpacesData,
  CreateSpaceData,
  CreateSpaceError,
  CreateSpaceResponse,
  DeleteSpaceData,
  DeleteSpaceError,
  DeleteSpaceResponse,
  GetSpaceData,
  UpdateSpaceData,
  UpdateSpaceError,
  UpdateSpaceResponse,
  GetUserSslkeysData,
  ListFabricVlanSubnetsData,
  CreateFabricVlanSubnetData,
  CreateFabricVlanSubnetError,
  CreateFabricVlanSubnetResponse,
  DeleteFabricVlanSubnetData,
  DeleteFabricVlanSubnetError,
  DeleteFabricVlanSubnetResponse,
  UpdateFabricVlanSubnetData,
  UpdateFabricVlanSubnetError,
  UpdateFabricVlanSubnetResponse,
  GetFabricVlanSubnetData,
  GetUserInfoData,
  ListUserSshkeysData,
  GetUserSshkeyData,
  ListUsersData,
  CreateUserData,
  CreateUserError,
  CreateUserResponse,
  GetUserData,
  UpdateUserData,
  UpdateUserError,
  UpdateUserResponse,
  ListFabricVlansData,
  CreateFabricVlanData,
  CreateFabricVlanError,
  CreateFabricVlanResponse,
  DeleteFabricVlanData,
  DeleteFabricVlanError,
  DeleteFabricVlanResponse,
  GetFabricVlanData,
  UpdateFabricVlanData,
  UpdateFabricVlanError,
  UpdateFabricVlanResponse,
  ListZonesData,
  CreateZoneData,
  CreateZoneError,
  CreateZoneResponse,
  DeleteZoneData,
  DeleteZoneError,
  DeleteZoneResponse,
  GetZoneData,
  UpdateZoneData,
  UpdateZoneError,
  UpdateZoneResponse,
} from "../types.gen";

type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean
): QueryKey<TOptions>[0] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return params;
};

export const accessTokenQueryKey = (options?: Options<AccessTokenData>) => [
  createQueryKey("accessToken", options),
];

export const accessTokenOptions = (options?: Options<AccessTokenData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await accessToken({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: accessTokenQueryKey(options),
  });
};

export const loginQueryKey = (options: Options<LoginData>) => [
  createQueryKey("login", options),
];

export const loginOptions = (options: Options<LoginData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await login({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: loginQueryKey(options),
  });
};

export const loginMutation = (options?: Partial<Options<LoginData>>) => {
  const mutationOptions: UseMutationOptions<
    LoginResponse,
    LoginError,
    Options<LoginData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await login({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const listEventsQueryKey = (options?: Options<ListEventsData>) => [
  createQueryKey("listEvents", options),
];

export const listEventsOptions = (options?: Options<ListEventsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listEvents({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listEventsQueryKey(options),
  });
};

export const listFabricsQueryKey = (options?: Options<ListFabricsData>) => [
  createQueryKey("listFabrics", options),
];

export const listFabricsOptions = (options?: Options<ListFabricsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listFabrics({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listFabricsQueryKey(options),
  });
};

export const createFabricQueryKey = (options: Options<CreateFabricData>) => [
  createQueryKey("createFabric", options),
];

export const createFabricOptions = (options: Options<CreateFabricData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await createFabric({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: createFabricQueryKey(options),
  });
};

export const createFabricMutation = (
  options?: Partial<Options<CreateFabricData>>
) => {
  const mutationOptions: UseMutationOptions<
    CreateFabricResponse,
    CreateFabricError,
    Options<CreateFabricData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await createFabric({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const deleteFabricMutation = (
  options?: Partial<Options<DeleteFabricData>>
) => {
  const mutationOptions: UseMutationOptions<
    DeleteFabricResponse,
    DeleteFabricError,
    Options<DeleteFabricData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await deleteFabric({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getFabricQueryKey = (options: Options<GetFabricData>) => [
  createQueryKey("getFabric", options),
];

export const getFabricOptions = (options: Options<GetFabricData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getFabric({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getFabricQueryKey(options),
  });
};

export const updateFabricMutation = (
  options?: Partial<Options<UpdateFabricData>>
) => {
  const mutationOptions: UseMutationOptions<
    UpdateFabricResponse,
    UpdateFabricError,
    Options<UpdateFabricData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await updateFabric({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const listInterfacesQueryKey = (
  options: Options<ListInterfacesData>
) => [createQueryKey("listInterfaces", options)];

export const listInterfacesOptions = (options: Options<ListInterfacesData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listInterfaces({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listInterfacesQueryKey(options),
  });
};

export const listFabricVlanSubnetIprangeQueryKey = (
  options: Options<ListFabricVlanSubnetIprangeData>
) => [createQueryKey("listFabricVlanSubnetIprange", options)];

export const listFabricVlanSubnetIprangeOptions = (
  options: Options<ListFabricVlanSubnetIprangeData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listFabricVlanSubnetIprange({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listFabricVlanSubnetIprangeQueryKey(options),
  });
};

export const createFabricVlanSubnetIprangeQueryKey = (
  options: Options<CreateFabricVlanSubnetIprangeData>
) => [createQueryKey("createFabricVlanSubnetIprange", options)];

export const createFabricVlanSubnetIprangeOptions = (
  options: Options<CreateFabricVlanSubnetIprangeData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await createFabricVlanSubnetIprange({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: createFabricVlanSubnetIprangeQueryKey(options),
  });
};

export const createFabricVlanSubnetIprangeMutation = (
  options?: Partial<Options<CreateFabricVlanSubnetIprangeData>>
) => {
  const mutationOptions: UseMutationOptions<
    CreateFabricVlanSubnetIprangeResponse,
    CreateFabricVlanSubnetIprangeError,
    Options<CreateFabricVlanSubnetIprangeData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await createFabricVlanSubnetIprange({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const deleteFabricVlanSubnetIprangeMutation = (
  options?: Partial<Options<DeleteFabricVlanSubnetIprangeData>>
) => {
  const mutationOptions: UseMutationOptions<
    DeleteFabricVlanSubnetIprangeResponse,
    DeleteFabricVlanSubnetIprangeError,
    Options<DeleteFabricVlanSubnetIprangeData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await deleteFabricVlanSubnetIprange({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const updateFabricVlanSubnetIprangeMutation = (
  options?: Partial<Options<UpdateFabricVlanSubnetIprangeData>>
) => {
  const mutationOptions: UseMutationOptions<
    UpdateFabricVlanSubnetIprangeResponse,
    UpdateFabricVlanSubnetIprangeError,
    Options<UpdateFabricVlanSubnetIprangeData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await updateFabricVlanSubnetIprange({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getFabricVlanSubnetIprangeQueryKey = (
  options: Options<GetFabricVlanSubnetIprangeData>
) => [createQueryKey("getFabricVlanSubnetIprange", options)];

export const getFabricVlanSubnetIprangeOptions = (
  options: Options<GetFabricVlanSubnetIprangeData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getFabricVlanSubnetIprange({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getFabricVlanSubnetIprangeQueryKey(options),
  });
};

export const getMachinePowerParametersQueryKey = (
  options: Options<GetMachinePowerParametersData>
) => [createQueryKey("getMachinePowerParameters", options)];

export const getMachinePowerParametersOptions = (
  options: Options<GetMachinePowerParametersData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getMachinePowerParameters({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getMachinePowerParametersQueryKey(options),
  });
};

export const listMachinePciDevicesQueryKey = (
  options: Options<ListMachinePciDevicesData>
) => [createQueryKey("listMachinePciDevices", options)];

export const listMachinePciDevicesOptions = (
  options: Options<ListMachinePciDevicesData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listMachinePciDevices({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listMachinePciDevicesQueryKey(options),
  });
};

export const listMachineUsbDevicesQueryKey = (
  options: Options<ListMachineUsbDevicesData>
) => [createQueryKey("listMachineUsbDevices", options)];

export const listMachineUsbDevicesOptions = (
  options: Options<ListMachineUsbDevicesData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listMachineUsbDevices({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listMachineUsbDevicesQueryKey(options),
  });
};

export const listMachinesQueryKey = (options?: Options<ListMachinesData>) => [
  createQueryKey("listMachines", options),
];

export const listMachinesOptions = (options?: Options<ListMachinesData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listMachines({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listMachinesQueryKey(options),
  });
};

export const listFabricVlanSubnetReservedIpsQueryKey = (
  options: Options<ListFabricVlanSubnetReservedIpsData>
) => [createQueryKey("listFabricVlanSubnetReservedIps", options)];

export const listFabricVlanSubnetReservedIpsOptions = (
  options: Options<ListFabricVlanSubnetReservedIpsData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listFabricVlanSubnetReservedIps({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listFabricVlanSubnetReservedIpsQueryKey(options),
  });
};

export const createFabricVlanSubnetReservedIpQueryKey = (
  options: Options<CreateFabricVlanSubnetReservedIpData>
) => [createQueryKey("createFabricVlanSubnetReservedIp", options)];

export const createFabricVlanSubnetReservedIpOptions = (
  options: Options<CreateFabricVlanSubnetReservedIpData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await createFabricVlanSubnetReservedIp({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: createFabricVlanSubnetReservedIpQueryKey(options),
  });
};

export const createFabricVlanSubnetReservedIpMutation = (
  options?: Partial<Options<CreateFabricVlanSubnetReservedIpData>>
) => {
  const mutationOptions: UseMutationOptions<
    CreateFabricVlanSubnetReservedIpResponse,
    CreateFabricVlanSubnetReservedIpError,
    Options<CreateFabricVlanSubnetReservedIpData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await createFabricVlanSubnetReservedIp({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const deleteFabricVlanSubnetReservedIpMutation = (
  options?: Partial<Options<DeleteFabricVlanSubnetReservedIpData>>
) => {
  const mutationOptions: UseMutationOptions<
    DeleteFabricVlanSubnetReservedIpResponse,
    DeleteFabricVlanSubnetReservedIpError,
    Options<DeleteFabricVlanSubnetReservedIpData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await deleteFabricVlanSubnetReservedIp({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const updateFabricVlanSubnetReservedIpMutation = (
  options?: Partial<Options<UpdateFabricVlanSubnetReservedIpData>>
) => {
  const mutationOptions: UseMutationOptions<
    UpdateFabricVlanSubnetReservedIpResponse,
    UpdateFabricVlanSubnetReservedIpError,
    Options<UpdateFabricVlanSubnetReservedIpData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await updateFabricVlanSubnetReservedIp({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getFabricVlanSubnetReservedIpQueryKey = (
  options: Options<GetFabricVlanSubnetReservedIpData>
) => [createQueryKey("getFabricVlanSubnetReservedIp", options)];

export const getFabricVlanSubnetReservedIpOptions = (
  options: Options<GetFabricVlanSubnetReservedIpData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getFabricVlanSubnetReservedIp({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getFabricVlanSubnetReservedIpQueryKey(options),
  });
};

export const listResourcePoolsQueryKey = (
  options?: Options<ListResourcePoolsData>
) => [createQueryKey("listResourcePools", options)];

export const listResourcePoolsOptions = (
  options?: Options<ListResourcePoolsData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listResourcePools({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listResourcePoolsQueryKey(options),
  });
};

export const createResourcePoolQueryKey = (
  options: Options<CreateResourcePoolData>
) => [createQueryKey("createResourcePool", options)];

export const createResourcePoolOptions = (
  options: Options<CreateResourcePoolData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await createResourcePool({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: createResourcePoolQueryKey(options),
  });
};

export const createResourcePoolMutation = (
  options?: Partial<Options<CreateResourcePoolData>>
) => {
  const mutationOptions: UseMutationOptions<
    CreateResourcePoolResponse,
    CreateResourcePoolError,
    Options<CreateResourcePoolData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await createResourcePool({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getResourcePoolQueryKey = (
  options: Options<GetResourcePoolData>
) => [createQueryKey("getResourcePool", options)];

export const getResourcePoolOptions = (
  options: Options<GetResourcePoolData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getResourcePool({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getResourcePoolQueryKey(options),
  });
};

export const updateResourcePoolMutation = (
  options?: Partial<Options<UpdateResourcePoolData>>
) => {
  const mutationOptions: UseMutationOptions<
    UpdateResourcePoolResponse,
    UpdateResourcePoolError,
    Options<UpdateResourcePoolData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await updateResourcePool({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const listSpacesQueryKey = (options?: Options<ListSpacesData>) => [
  createQueryKey("listSpaces", options),
];

export const listSpacesOptions = (options?: Options<ListSpacesData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listSpaces({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listSpacesQueryKey(options),
  });
};

export const createSpaceQueryKey = (options: Options<CreateSpaceData>) => [
  createQueryKey("createSpace", options),
];

export const createSpaceOptions = (options: Options<CreateSpaceData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await createSpace({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: createSpaceQueryKey(options),
  });
};

export const createSpaceMutation = (
  options?: Partial<Options<CreateSpaceData>>
) => {
  const mutationOptions: UseMutationOptions<
    CreateSpaceResponse,
    CreateSpaceError,
    Options<CreateSpaceData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await createSpace({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const deleteSpaceMutation = (
  options?: Partial<Options<DeleteSpaceData>>
) => {
  const mutationOptions: UseMutationOptions<
    DeleteSpaceResponse,
    DeleteSpaceError,
    Options<DeleteSpaceData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await deleteSpace({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getSpaceQueryKey = (options: Options<GetSpaceData>) => [
  createQueryKey("getSpace", options),
];

export const getSpaceOptions = (options: Options<GetSpaceData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getSpace({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getSpaceQueryKey(options),
  });
};

export const updateSpaceMutation = (
  options?: Partial<Options<UpdateSpaceData>>
) => {
  const mutationOptions: UseMutationOptions<
    UpdateSpaceResponse,
    UpdateSpaceError,
    Options<UpdateSpaceData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await updateSpace({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getUserSslkeysQueryKey = (
  options?: Options<GetUserSslkeysData>
) => [createQueryKey("getUserSslkeys", options)];

export const getUserSslkeysOptions = (
  options?: Options<GetUserSslkeysData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getUserSslkeys({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getUserSslkeysQueryKey(options),
  });
};

export const listFabricVlanSubnetsQueryKey = (
  options: Options<ListFabricVlanSubnetsData>
) => [createQueryKey("listFabricVlanSubnets", options)];

export const listFabricVlanSubnetsOptions = (
  options: Options<ListFabricVlanSubnetsData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listFabricVlanSubnets({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listFabricVlanSubnetsQueryKey(options),
  });
};

export const createFabricVlanSubnetQueryKey = (
  options: Options<CreateFabricVlanSubnetData>
) => [createQueryKey("createFabricVlanSubnet", options)];

export const createFabricVlanSubnetOptions = (
  options: Options<CreateFabricVlanSubnetData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await createFabricVlanSubnet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: createFabricVlanSubnetQueryKey(options),
  });
};

export const createFabricVlanSubnetMutation = (
  options?: Partial<Options<CreateFabricVlanSubnetData>>
) => {
  const mutationOptions: UseMutationOptions<
    CreateFabricVlanSubnetResponse,
    CreateFabricVlanSubnetError,
    Options<CreateFabricVlanSubnetData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await createFabricVlanSubnet({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const deleteFabricVlanSubnetMutation = (
  options?: Partial<Options<DeleteFabricVlanSubnetData>>
) => {
  const mutationOptions: UseMutationOptions<
    DeleteFabricVlanSubnetResponse,
    DeleteFabricVlanSubnetError,
    Options<DeleteFabricVlanSubnetData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await deleteFabricVlanSubnet({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const updateFabricVlanSubnetMutation = (
  options?: Partial<Options<UpdateFabricVlanSubnetData>>
) => {
  const mutationOptions: UseMutationOptions<
    UpdateFabricVlanSubnetResponse,
    UpdateFabricVlanSubnetError,
    Options<UpdateFabricVlanSubnetData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await updateFabricVlanSubnet({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getFabricVlanSubnetQueryKey = (
  options: Options<GetFabricVlanSubnetData>
) => [createQueryKey("getFabricVlanSubnet", options)];

export const getFabricVlanSubnetOptions = (
  options: Options<GetFabricVlanSubnetData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getFabricVlanSubnet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getFabricVlanSubnetQueryKey(options),
  });
};

export const getUserInfoQueryKey = (options?: Options<GetUserInfoData>) => [
  createQueryKey("getUserInfo", options),
];

export const getUserInfoOptions = (options?: Options<GetUserInfoData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getUserInfo({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getUserInfoQueryKey(options),
  });
};

export const listUserSshkeysQueryKey = (
  options?: Options<ListUserSshkeysData>
) => [createQueryKey("listUserSshkeys", options)];

export const listUserSshkeysOptions = (
  options?: Options<ListUserSshkeysData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listUserSshkeys({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listUserSshkeysQueryKey(options),
  });
};

export const getUserSshkeyQueryKey = (options: Options<GetUserSshkeyData>) => [
  createQueryKey("getUserSshkey", options),
];

export const getUserSshkeyOptions = (options: Options<GetUserSshkeyData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getUserSshkey({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getUserSshkeyQueryKey(options),
  });
};

export const listUsersQueryKey = (options?: Options<ListUsersData>) => [
  createQueryKey("listUsers", options),
];

export const listUsersOptions = (options?: Options<ListUsersData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listUsers({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listUsersQueryKey(options),
  });
};

export const createUserQueryKey = (options: Options<CreateUserData>) => [
  createQueryKey("createUser", options),
];

export const createUserOptions = (options: Options<CreateUserData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await createUser({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: createUserQueryKey(options),
  });
};

export const createUserMutation = (
  options?: Partial<Options<CreateUserData>>
) => {
  const mutationOptions: UseMutationOptions<
    CreateUserResponse,
    CreateUserError,
    Options<CreateUserData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await createUser({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getUserQueryKey = (options: Options<GetUserData>) => [
  createQueryKey("getUser", options),
];

export const getUserOptions = (options: Options<GetUserData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getUser({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getUserQueryKey(options),
  });
};

export const updateUserMutation = (
  options?: Partial<Options<UpdateUserData>>
) => {
  const mutationOptions: UseMutationOptions<
    UpdateUserResponse,
    UpdateUserError,
    Options<UpdateUserData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await updateUser({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const listFabricVlansQueryKey = (
  options: Options<ListFabricVlansData>
) => [createQueryKey("listFabricVlans", options)];

export const listFabricVlansOptions = (
  options: Options<ListFabricVlansData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listFabricVlans({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listFabricVlansQueryKey(options),
  });
};

export const createFabricVlanQueryKey = (
  options: Options<CreateFabricVlanData>
) => [createQueryKey("createFabricVlan", options)];

export const createFabricVlanOptions = (
  options: Options<CreateFabricVlanData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await createFabricVlan({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: createFabricVlanQueryKey(options),
  });
};

export const createFabricVlanMutation = (
  options?: Partial<Options<CreateFabricVlanData>>
) => {
  const mutationOptions: UseMutationOptions<
    CreateFabricVlanResponse,
    CreateFabricVlanError,
    Options<CreateFabricVlanData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await createFabricVlan({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const deleteFabricVlanMutation = (
  options?: Partial<Options<DeleteFabricVlanData>>
) => {
  const mutationOptions: UseMutationOptions<
    DeleteFabricVlanResponse,
    DeleteFabricVlanError,
    Options<DeleteFabricVlanData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await deleteFabricVlan({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getFabricVlanQueryKey = (options: Options<GetFabricVlanData>) => [
  createQueryKey("getFabricVlan", options),
];

export const getFabricVlanOptions = (options: Options<GetFabricVlanData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getFabricVlan({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getFabricVlanQueryKey(options),
  });
};

export const updateFabricVlanMutation = (
  options?: Partial<Options<UpdateFabricVlanData>>
) => {
  const mutationOptions: UseMutationOptions<
    UpdateFabricVlanResponse,
    UpdateFabricVlanError,
    Options<UpdateFabricVlanData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await updateFabricVlan({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const listZonesQueryKey = (options?: Options<ListZonesData>) => [
  createQueryKey("listZones", options),
];

export const listZonesOptions = (options?: Options<ListZonesData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listZones({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listZonesQueryKey(options),
  });
};

export const createZoneQueryKey = (options: Options<CreateZoneData>) => [
  createQueryKey("createZone", options),
];

export const createZoneOptions = (options: Options<CreateZoneData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await createZone({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: createZoneQueryKey(options),
  });
};

export const createZoneMutation = (
  options?: Partial<Options<CreateZoneData>>
) => {
  const mutationOptions: UseMutationOptions<
    CreateZoneResponse,
    CreateZoneError,
    Options<CreateZoneData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await createZone({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const deleteZoneMutation = (
  options?: Partial<Options<DeleteZoneData>>
) => {
  const mutationOptions: UseMutationOptions<
    DeleteZoneResponse,
    DeleteZoneError,
    Options<DeleteZoneData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await deleteZone({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getZoneQueryKey = (options: Options<GetZoneData>) => [
  createQueryKey("getZone", options),
];

export const getZoneOptions = (options: Options<GetZoneData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getZone({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getZoneQueryKey(options),
  });
};

export const updateZoneMutation = (
  options?: Partial<Options<UpdateZoneData>>
) => {
  const mutationOptions: UseMutationOptions<
    UpdateZoneResponse,
    UpdateZoneError,
    Options<UpdateZoneData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await updateZone({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};
