name: sitespeed.io
on:
  push:
    branches:
      - main
      - "3.6"
      - "3.7"
      - "3.8"
      - "*sitespeed*"
  workflow_dispatch:
    inputs:
      build-from-source:
        description: "Build the MAAS backend from source instead of installing its published snap"
        type: boolean
        default: false
jobs:
  run-sitespeed:
    name: Run sitespeed.io
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
    env:
      MAAS_DOMAIN: localhost
      MAAS_URL: http://localhost:5240
    steps:
      - uses: actions/checkout@main
      - name: Use Node.js from .nvmrc
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
      - name: Build production UI
        run: yarn build
      - name: Setup MAAS
        uses: canonical/setup-maas@main
        with:
          branch: ${{ contains(github.ref_name, 'sitespeed') && 'main' || github.ref_name }}
          build-from-source: ${{ inputs.build-from-source || false }}
          maas-url: ${{ env.MAAS_URL }}/MAAS
          use-maasdb-dump: true
          maasdb-dump-url: https://github.com/canonical/maas-ui-testing/raw/main/db/maasdb-${{ (github.ref_name == '3.6' || github.ref_name == '3.7') && '24.04' || '26.04' }}-master-1000.dump
      - name: Create MAAS admin
        run: lxc exec maas-backend -- maas createadmin --username=admin --password=test --email=fake@example.org
      - name: Login MAAS admin
        run: |
          API_KEY=$(lxc exec maas-backend -- maas apikey --username=admin)
          lxc exec maas-backend -- maas login admin http://localhost:5240/MAAS "$API_KEY"
      - name: Wait for MAAS boot resources
        shell: bash
        run: while [ $(lxc exec maas-backend -- maas admin boot-resources is-importing | cat) == "true" ]; do sleep 10; done; echo "syncing finished"
      - name: Serve production UI
        env:
          NODE_ENV: production
          STATIC_DEMO: "true"
        run: node scripts/proxy.js > sitespeed.io/ui.log 2>&1 &
      - name: Wait for production UI
        run: yarn wait-on-ui --timeout 120000
      - name: Run sitespeed.io tests
        run: yarn sitespeed:ci --browsertime.domain=${{env.MAAS_DOMAIN}} --browsertime.port=8400
      - name: Collect MAAS logs
        if: failure()
        shell: bash
        run: lxc exec maas-backend -- journalctl -u snap.maas.pebble.service --since="1 hour ago" > sitespeed.io/maas_logs.txt
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: maas_logs
          path: |
            sitespeed.io/maas_logs.txt
            sitespeed.io/ui.log
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: sitespeed.io-results
          path: sitespeed.io/results
